### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by MohammadRezaei92** [bytedeco/javacv#1477]
I have out of memory exception on some devices
Android 9 (SDK 28)

`Caused by: java.lang.OutOfMemoryError: 
  at org.bytedeco.javacpp.BytePointer.<init> (BytePointer.java:132)
  at FFmpegFrameFilter.pullImage (FFmpegFrameFilter.java:770)
  at FFmpegFrameFilter.pull (FFmpegFrameFilter.java:723`

**Comment by saudet** [comment]
This has been fixed. Please try again with JavaCV 1.5.4-SNAPSHOT: http://bytedeco.org/builds/

**Comment by MohammadRezaei92** [comment]
> This has been fixed. Please try again with JavaCV 1.5.4-SNAPSHOT: http://bytedeco.org/builds/
I see, I tried to use the snapshot but I failed. Android studio couldn't load snapshot dependencies. Would you release new version?

**Comment by saudet** [comment]
The snapshots have been fixed just now, please try again: http://bytedeco.org/builds/

**Comment by MohammadRezaei92** [comment]
I've got this error yet
`More than one file was found with OS independent path 'META-INF/native-image/ios-x86_64/jnijavacpp/reflect-config.json'.
`

**Comment by saudet** [comment]
You can skip those files, they are not useful for Android.

**Comment by MohammadRezaei92** [comment]
And this error
`Failed to resolve: ffmpeg-4.3-1.5.4-SNAPSHOT-android-arm`

**Comment by saudet** [comment]
I'm sorry, I forgot to update JavaCV itself. It should work now, please try again: http://bytedeco.org/builds/

**Comment by MohammadRezaei92** [comment]
> I've got this error yet
> `More than one file was found with OS independent path 'META-INF/native-image/ios-x86_64/jnijavacpp/reflect-config.json'. `

Still get this error.
I couldn't find any `packagingOptions exclude` item that can fix this issue.

**Comment by saudet** [comment]
See issue #353 for some examples.

**Comment by MohammadRezaei92** [comment]
Another outOfMemory exception on

`
Physical memory usage is too high: physicalBytes (523M) > maxPhysicalBytes (512M)
org.bytedeco.javacpp.Pointer.deallocator (Pointer.java:682)
org.bytedeco.javacpp.Pointer.init (Pointer.java:127)
org.bytedeco.ffmpeg.global.avutil.av_d2q (avutil.java)
org.bytedeco.javacv.FFmpegFrameFilter.startVideoUnsafe (FFmpegFrameFilter.java:321)
org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe (FFmpegFrameFilter.java:303)
org.bytedeco.javacv.FFmpegFrameFilter.start (FFmpegFrameFilter.java:278)
`

**Comment by saudet** [comment]
Increase the amount of memory available to your app.

**Comment by saudet** [comment]
Please make sure to "largeHeap" to "true": https://developer.android.com/guide/topics/manifest/application-element

**Comment by MohammadRezaei92** [comment]
> Please make sure to set "largeHeap" to "true": https://developer.android.com/guide/topics/manifest/application-element

It's true

**Comment by saudet** [comment]
We can also set the "org.bytedeco.javacpp.maxbytes" system property to "0" to skip that check, but it sounds like your device just doesn't have enough memory anyway.

**Comment by MohammadRezaei92** [comment]
There is device info of several devices that this error occurs on them:

 Brand: samsung
Model: Galaxy S6 edge+
Orientation: Portrait
RAM free: 651.1 MB
Disk free: 22.41 GB 
------------------------------
 Brand: OnePlus
Model: OnePlus 7T Pro 5G
Orientation: Portrait
RAM free: 4.45 GB
Disk free: 122.86 GB 
--------------------------------
 Brand: LGE
Model: LG Stylo 4
Orientation: Portrait
RAM free: 330.45 MB
Disk free: 6.06 GB

**Comment by saudet** [comment]
> We can also set the "org.bytedeco.javacpp.maxbytes" system property to "0" to skip that check, but it sounds like your device just doesn't have enough memory anyway.

**Comment by MohammadRezaei92** [comment]
> We can also set the "org.bytedeco.javacpp.maxbytes" system property to "0" to skip that check, but it sounds like your device just doesn't have enough memory anyway.

I still have outOfMemoryException despite set the "org.bytedeco.javacpp.maxbytes" system property to "0"

**Comment by nailshakurov** [comment]
> > We can also set the "org.bytedeco.javacpp.maxbytes" system property to "0" to skip that check, but it sounds like your device just doesn't have enough memory anyway.
> 
> I still have outOfMemoryException despite set the "org.bytedeco.javacpp.maxbytes" system property to "0"

Did you fix the problem?

**Comment by saudet** [comment]
What does the stack trace look like?

**Comment by nailshakurov** [comment]
> Как выглядит трассировка стека?

[logs.txt](https://github.com/bytedeco/javacv/files/6493400/logs.txt)
https://gist.github.com/nailshakurov/ac878503939c56b9a3ba4304a204c6c1

**Comment by saudet** [comment]
I'm not seeing OutOfMemoryError anywhere in the log.

**Comment by nailshakurov** [comment]
> I'm not seeing OutOfMemoryError anywhere in the log.

The application eats up all memory and the android deletes the application process.

**Comment by nailshakurov** [comment]
![image](https://user-images.githubusercontent.com/11345578/118497252-f49cd280-b735-11eb-941f-9bf144b0d083.png)

**Comment by XuXuanXu** [comment]
> I'm sorry, I forgot to update JavaCV itself. It should work now, please try again: http://bytedeco.org/builds/

I update JavaCV 1.5.6 SNAPSHOT,But Memory grows slowly,From the original 480M to 560M。At last, java.lang.OutOfMemoryError:

**Comment by saudet** [comment]
@XuXuanXu Could you provide a small self-contained program to reproduce this?

**Comment by XuXuanXu** [comment]
This is my code： 
public static InputStream videoImage(InputStream videoStream) throws Exception {
		FFmpegFrameGrabber ff = null;
		Frame f;
        Java2DFrameConverter converter = null;
        InputStream is = null;
        ByteArrayOutputStream bs = new ByteArrayOutputStream();
        ImageOutputStream imOut;
        int i = 0;
        try {
        	ff = new FFmpegFrameGrabber(videoStream);
        	ff.start();
        	converter = new Java2DFrameConverter();
        	int ffLength = ff != null ? ff.getLengthInFrames() : i;
    		while (i <= ffLength) {
    			f = ff.grabImage();
    			//Get the sixth frame
    			if( i > 5  && (f != null && f.image != null)){
    				BufferedImage bimage = converter.getBufferedImage(f);
    				imOut = ImageIO.createImageOutputStream(bs);
    				ImageIO.write(bimage, BaseConstant.EMERTENCY_COVER_SUFFIX, imOut);
    				is = new ByteArrayInputStream(bs.toByteArray());
    				break;
    			}
    			i++;
    		}
        } catch (Exception e) {
            //...
        } finally {
        	IoUtils.closeQuietly(videoStream);
            try {
                if (ff != null) {
                    ff.close();
                }
                if(converter != null) {
                	converter.close();
                }
            } catch (FrameGrabber.Exception e) {
                //....
            }
        }
        return is;		
    }

**Comment by XuXuanXu** [comment]
> I'm sorry, I forgot to update JavaCV itself. It should work now, please try again: http://bytedeco.org/builds/

**Comment by saudet** [comment]
@XuXuanXu You'll need to set the maximumSize of FFmpegFrameGrabber to 0...

**Comment by XuXuanXu** [comment]
Let me try

**Comment by XuXuanXu** [comment]
@saudet I regret to tell you that it didn't work to set FFmpegFrameGrabber  to 0, That is new FFmpegFrameGrabber(videoStream, 0)

**Comment by saudet** [comment]
@XuXuanXu Ok, but you still need to make sure that your OutputStream and InputStream are not ones leaking memory. How did you confirm this? One way that you could confirm that is by trying to reproduce this issue using normal File objects instead. If you are able to recreate this issue with File objects, please  provide a small self-contained program to reproduce this using File objects instead.

**Comment by saudet** [comment]
In any case, commit https://github.com/bytedeco/javacpp/commit/343045d9c3f01856691c9b8576cbc3e98ee6e369 probably works around the original issue,
so please give it a try with the snapshots: http://bytedeco.org/builds/
If anyone is still having problems with this though, let's continue at issue https://github.com/bytedeco/javacpp/issues/468.

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp/issues/468

**Comment by XuXuanXu** [comment]
@saudet Thank You，Let me try
