### ISSUE TITLE
Memory leak found in FFmpegFrameRecorder

### ISSUE THREAD

**Issue by whz-NJ** [bytedeco/javacv#2356]
Dear author,
    I met a native off-heap memory leak problem when I try to convert pcm audio to mp3 format, and javacv/javacpp used is 1.5.9 version, ffmpeg is 6.0-1.5.9. Following is the code, and even if I delete the sentences: new FFmpegFrameRecorder/start (recorder)/stop (recorder) and the internal packet capture while loop, only keep the sentences: start (grabber) and stop (grabber), there is still a memory leak, please help to check, thank you very much!

import org.apache.commons.io.IOUtils;
import org.bytedeco.ffmpeg.global.avcodec;
import org.bytedeco.javacv.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.concurrent.CountDownLatch;

public class Test {
    private static final Logger LOGGER = LoggerFactory.getLogger(Test.class);

    private static boolean start(FrameGrabber grabber) {
        try {
            grabber.start();
            return true;
        } catch (org.bytedeco.javacv.FrameGrabber.Exception e2) {
            e2.printStackTrace();
            try {
                LOGGER.error("首次打开抓取器失败，准备重启抓取器...");
                grabber.restart();
                return true;
            } catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
                try {
                    LOGGER.error("重启抓取器失败，正在关闭抓取器...", e);
                    grabber.stop();
                } catch (org.bytedeco.javacv.FrameGrabber.Exception e1) {
                    LOGGER.error("停止抓取器失败！", e1);
                }
            }

        }
        return false;
    }

    private static boolean start(FrameRecorder recorder) {
        try {
            recorder.start();
            return true;
        } catch (Exception e2) {
            try {
                LOGGER.error("首次打开录制器失败！准备重启录制器...", e2);
                recorder.stop();
                recorder.start();
                return true;
            } catch (Exception e) {
                try {
                    LOGGER.error("重启录制器失败！正在停止录制器...", e);
                    recorder.stop();
                } catch (Exception e1) {
                    LOGGER.error("关闭录制器失败！", e);
                }
            }
        }
        return false;
    }

    private static boolean stop(FrameGrabber grabber) {
        try {
            grabber.flush();
            return true;
        } catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
            return false;
        } finally {
            try {
                grabber.stop();
                grabber.release();
            } catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
                LOGGER.error("关闭抓取器失败", e);
            }
        }
    }

    private static boolean stop(FrameRecorder recorder) {
        try {
            recorder.flush();
            return true;
        } catch (Exception e) {
            return false;
        } finally {
            try {
                recorder.stop();
                recorder.release();
            } catch (Exception e) {

            }
        }
    }

    public static byte[] convert2Bytes(InputStream inputStream,
                                              String fromType, String toType, String sample_rate) {
        FFmpegFrameRecorder recorder = null;
        FFmpegFrameGrabber grabber = null;
        Frame audioSamples = null;
        ByteArrayOutputStream swapStream = null;
        try {
            grabber = new FFmpegFrameGrabber(inputStream);
            if ("pcm".equals(fromType)) {
                grabber.setAudioCodec(avcodec.AV_CODEC_ID_PCM_S16LE);
                grabber.setFormat("s16le");
            } else if ("mp3".equals(fromType)) {
                grabber.setAudioCodec(avcodec.AV_CODEC_ID_MP3);
                grabber.setFormat("mp3");
            } else if ("wav".equals(fromType)) {
                grabber.setAudioCodec(avcodec.AV_CODEC_ID_ADPCM_IMA_WAV);
                grabber.setFormat("wav");
            } else if ("opus".equals(fromType)) {
                grabber.setAudioCodec(avcodec.AV_CODEC_ID_MP2);
                grabber.setFormat("ogg");
            }

            int sampleRate = Integer.valueOf(sample_rate);
            grabber.setSampleRate(sampleRate);
            if (start(grabber)) {
                swapStream = new ByteArrayOutputStream();
                recorder = new FFmpegFrameRecorder(swapStream, 1);
                recorder.setAudioOption("crf", "0");
                recorder.setAudioBitrate(16000);
                recorder.setAudioChannels(1);
                recorder.setSampleRate(sampleRate);
                recorder.setAudioQuality(0);
                if ("mp3".equals(toType)) {
                    recorder.setFormat("mp3");
                }
                if ("wav".equals(toType)) {
                    recorder.setFormat("wav");
                }
                if ("pcm".equals(toType) || "raw".equals(toType)) {
                    recorder.setFormat("s16le");
                }

                recorder.setAudioOption("aq", "10");
                // 开启录制器
                if (start(recorder)) {
                    try {
                        while ((audioSamples = grabber.grab()) != null) {
                            recorder.setTimestamp(grabber.getTimestamp());
                            recorder.record(audioSamples);
                            audioSamples.close();
                        }
                    } catch (org.bytedeco.javacv.FrameGrabber.Exception e1) {
                        LOGGER.error("抓取失败", e1);
                    } catch (Exception e) {
                        LOGGER.error("录制失败", e);
                    }
                }
            }
        } finally {
            if (grabber != null) {
                try {
                    stop(grabber);
                } catch (Exception e) {
                    LOGGER.error("grabber stop error", e);
                }
            }
            if (recorder != null) {
                try {
                    stop(recorder);
                } catch (Exception e) {
                    LOGGER.error("recorder stop error", e);
                }
            }
        }
        byte[] result = swapStream.toByteArray();
        IOUtils.closeQuietly(inputStream);
        IOUtils.closeQuietly(swapStream);
        return result;
    }

    public static void main(String[] args) throws Exception {
        System.setProperty("org.bytedeco.javacpp.logger.debug", "true");

        String inputPcmFile = "C:\\audios\\test_16000.pcm";
        int retries = 1;
        int ncp = 1;
        if(args != null && args.length == 3) {
            inputPcmFile = args[0];
            ncp = Integer.parseInt(args[1]);
            retries = Integer.parseInt(args[2]);
        }

        final CountDownLatch cdl = new CountDownLatch(ncp);
        String finalInputFile = inputPcmFile;

        byte[] pcmBytes = Files.readAllBytes(Paths.get(finalInputFile));
        int finalRetries = retries;
        for(int i = 0; i < ncp; i++) {
            Thread thread = new Thread(() -> {
                for (int j = 0; j < finalRetries; j++) {
                    try {
                        ByteArrayInputStream resultInputStream = new ByteArrayInputStream(pcmBytes);
                        byte[] mp3Bytes = convert2Bytes(resultInputStream, "pcm", "mp3", "16000");
                    } catch (Exception e) {
                        System.err.println("exception occurs: " + e.getClass().getCanonicalName());
                    }
                }
                cdl.countDown();
            });
            thread.start();
        }

        try {
            cdl.await();//需要捕获异常，当其中线程数为0时这里才会继续运行
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.12

**Comment by whz-NJ** [comment]
Hello saudet,
    When I upgrade JavaCV to 1.5.12, failed to startup, and following error printed. Could you tell me which version of centOS or Ubuntu support JavaCV 1.5.12, or how to compile JavaCV to fit my environment?

Debug: Failed to load for va@.1: java.lang.UnsatisfiedLinkError: no va in java.library.path
Debug: Loading /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2
Debug: Failed to load /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2)
Debug: Loading library drm
Debug: Failed to load for drm@.2: java.lang.UnsatisfiedLinkError: no drm in java.library.path
Debug: Loading /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so
Debug: Failed to load /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so: libva.so.2: cannot open shared object file: No such file or directory
Debug: Loading library va-drm
Debug: Failed to load for va-drm@.1: java.lang.UnsatisfiedLinkError: no va-drm in java.library.path
Debug: Loading /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.59
Debug: Failed to load /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.59: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.59: libva-drm.so.2: cannot open shared object file: No such file or directory
Debug: Loading library avutil
Debug: Failed to load for avutil@.59: java.lang.UnsatisfiedLinkError: no avutil in java.library.path
Debug: Loading /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
Debug: Failed to load /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: libva-drm.so.2: cannot open shared object file: No such file or directory
Debug: Loading library jniavutil
Debug: Failed to load for jniavutil: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Debug: Loading /root/.javacpp/cache/javacpp-1.5.12-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
Debug: Failed to load /root/.javacpp/cache/javacpp-1.5.12-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/javacpp-1.5.12-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /root/.javacpp/cache/javacpp-1.5.12-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so)
Debug: Loading library jnijavacpp
Debug: Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Debug: Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Exception in thread "Thread-1" Exception in thread "Thread-5" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1289)

**Comment by saudet** [comment]
That's been fixed in commit https://github.com/bytedeco/javacpp-presets/commit/03a05d68e603489b37c47aaa2d114699fef9820f
Please try again with the snapshots:
https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/org/bytedeco

**Comment by whz-NJ** [comment]
Hello saudet,
    I upgrade JavaCPP as 1.5.12-SNAPSHOT, JavaCV as 1.5.12, ffmpeg as 7.1.1-1.5.12, still failed to startup, and following error printed: 

Debug: Failed to load /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2)
Debug: Loading library drm
Debug: Failed to load for drm@.2: java.lang.UnsatisfiedLinkError: no drm in java.library.path
Debug: Loading /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so
Debug: Failed to load /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so: libva.so.2: cannot open shared object file: No such file or directory
Debug: Loading library va-drm
Debug: Failed to load for va-drm@.1: java.lang.UnsatisfiedLinkError: no va-drm in java.library.path
Debug: Loading /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.59
Debug: Failed to load /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.59: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.59: libva-drm.so.2: cannot open shared object file: No such file or directory
Debug: Loading library avutil
Debug: Failed to load for avutil@.59: java.lang.UnsatisfiedLinkError: no avutil in java.library.path
Debug: Loading /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
Debug: Failed to load /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-7.1.1-1.5.12-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: libva-drm.so.2: cannot open shared object file: No such file or directory
Debug: Loading library jniavutil
Debug: Failed to load for jniavutil: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Debug: Locking /root/.javacpp/cache before extracting
Debug: Extracting jar:file:/root/javacv_test-1.0-SNAPSHOT.jar!/BOOT-INF/lib/javacpp-1.5.12-SNAPSHOT-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
Debug: Loading /root/.javacpp/cache/javacpp-1.5.12-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
Debug: Failed to load /root/.javacpp/cache/javacpp-1.5.12-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/javacpp-1.5.12-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /root/.javacpp/cache/javacpp-1.5.12-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so)
Debug: Loading library jnijavacpp
Debug: Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Debug: Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Exception in thread "Thread-1" Exception in thread "Thread-3" Exception in thread "Thread-2" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
        at java.lang.Class.forName0(Native Method)

**Comment by whz-NJ** [comment]
Hello saudet,
    Try again with the snapshots, here which component's snapshot version does this refer to? JavaCPP or ffmpeg? Could you tell me the exact version number?

**Comment by saudet** [comment]
With JavaCV 1.5.13-SNAPSHOT

**Comment by whz-NJ** [comment]
Hello saudet,
    I tried JavaCV 1.5.13-SNAPSHOT, still failed to startup, following is the error printed:

Debug: Extracting jar:file:/root/javacv_test-1.0-SNAPSHOT.jar!/BOOT-INF/lib/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar!/org/bytedeco/ffmpeg/linux-x86_64/libva.so.2
Debug: Loading /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva.so.2
Debug: Failed to load /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva.so.2: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva.so.2: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva.so.2)
Debug: Loading library va
Debug: Failed to load for va@.2: java.lang.UnsatisfiedLinkError: no va in java.library.path
Debug: Locking /root/.javacpp/cache before extracting
Debug: Extracting jar:file:/root/javacv_test-1.0-SNAPSHOT.jar!/BOOT-INF/lib/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar!/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2
Debug: Loading /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2
Debug: Failed to load /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libdrm.so.2)
Debug: Loading library drm
Debug: Failed to load for drm@.2: java.lang.UnsatisfiedLinkError: no drm in java.library.path
Debug: Locking /root/.javacpp/cache before extracting
Debug: Extracting jar:file:/root/javacv_test-1.0-SNAPSHOT.jar!/BOOT-INF/lib/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar!/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so.2
Debug: Loading /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so.2
Debug: Failed to load /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so.2: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libva-drm.so.2: libva.so.2: cannot open shared object file: No such file or directory
Debug: Loading library va-drm
Debug: Failed to load for va-drm@.2: java.lang.UnsatisfiedLinkError: no va-drm in java.library.path
Debug: Locking /root/.javacpp/cache before extracting
Debug: Extracting jar:file:/root/javacv_test-1.0-SNAPSHOT.jar!/BOOT-INF/lib/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar!/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.60
Debug: Loading /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.60
Debug: Failed to load /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.60: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.60: libva-drm.so.2: cannot open shared object file: No such file or directory
Debug: Loading library avutil
Debug: Failed to load for avutil@.60: java.lang.UnsatisfiedLinkError: no avutil in java.library.path
Debug: Locking /root/.javacpp/cache before extracting
Debug: Extracting jar:file:/root/javacv_test-1.0-SNAPSHOT.jar!/BOOT-INF/lib/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar!/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
Debug: Loading /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so
Debug: Failed to load /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/ffmpeg-8.0-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libjniavutil.so: libva-drm.so.2: cannot open shared object file: No such file or directory
Debug: Loading library jniavutil
Debug: Failed to load for jniavutil: java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Debug: Locking /root/.javacpp/cache before extracting
Debug: Extracting jar:file:/root/javacv_test-1.0-SNAPSHOT.jar!/BOOT-INF/lib/javacpp-1.5.13-SNAPSHOT-linux-x86_64.jar!/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
Debug: Loading /root/.javacpp/cache/javacpp-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
Debug: Failed to load /root/.javacpp/cache/javacpp-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/javacpp-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /root/.javacpp/cache/javacpp-1.5.13-SNAPSHOT-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so)
Debug: Loading library jnijavacpp
Debug: Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Debug: Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.ffmpeg.global.avutil
Exception in thread "Thread-3" Exception in thread "Thread-1" Exception in thread "Thread-4" Exception in thread "Thread-2" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacv.FFmpegFrameGrabber
        at Test.convert2Bytes(Test.java:101)

**Comment by saudet** [comment]
That means you need a more recent version of Linux

**Comment by whz-NJ** [comment]
Hello saudet,
    Could you tell me which version of centOS or Ubuntu support JavaCV 1.5.13-SNAPSHOT?

**Comment by saudet** [comment]
Any version that hasn't reached EOL

**Comment by whz-NJ** [comment]
Hello saudet,
    I succeed upgrading  JavaCV to 1.5.13-SNAPSHOT in latest ubuntu docker container, but memory usage still keep increasing. I have called Pointer.trimMemory() at the end of function convert2Bytes(). Is there any other modification needed?

**Comment by whz-NJ** [comment]
Hello saudet,
    Is there any way to limit maximum memory usage of JavaCV/JavaCPP/ffmpeg component?

**Comment by saudet** [comment]
Sure: https://github.com/bytedeco/javacpp/wiki/System-Properties

**Comment by whz-NJ** [comment]
Hello saudet,
    Cloud you give me some example JavaCPP source code, which can be used to convert audio from pcm format to mp3 format?

**Comment by saudet** [comment]
We can easily accomplish this with the ffmpeg program:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by whz-NJ** [comment]
Hello saudet,
    I found the source code which caused the memory leak with valgrind, the output of valgrind is as following, it seems that FFmpegFrameRecorder.startUnsafe calls a native method avformat_alloc_output_context2 which defined in avformat, in the native method, calls av_strdup, and I fixed it by setting FFmpegFrameRecorder.filename as null to avoid calling av_strdup(since in my case, I initialized FFmpegFrameRecorder with ByteArrayOutputStream, and filename is no need). Please  help to check if this issue can be resolved in official version? thanks!

<img width="1242" height="224" alt="Image" src="https://github.com/user-attachments/assets/a4103a6b-e93e-4b7e-a12f-b06eec8cf6d6" />

**Comment by saudet** [comment]
Sure, please open a pull request with the change! Thanks

**Comment by cyfcyf734-ui** [comment]
> Hello saudet, I found the source code which caused the memory leak with valgrind, the output of valgrind is as following, it seems that FFmpegFrameRecorder.startUnsafe calls a native method avformat_alloc_output_context2 which defined in avformat, in the native method, calls av_strdup, and I fixed it by setting FFmpegFrameRecorder.filename as null to avoid calling av_strdup(since in my case, I initialized FFmpegFrameRecorder with ByteArrayOutputStream, and filename is no need). Please help to check if this issue can be resolved in official version? thanks!
> 
> <img alt="Image" width="1242" height="224" src="https://private-user-images.githubusercontent.com/41171402/494797137-a4103a6b-e93e-4b7e-a12f-b06eec8cf6d6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMwMjM2MzcsIm5iZiI6MTc2MzAyMzMzNywicGF0aCI6Ii80MTE3MTQwMi80OTQ3OTcxMzctYTQxMDNhNmItZTkzZS00YjdlLWExMmYtYjA2ZWVjOGNmNmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTEzVDA4NDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmYxNDAzMTIxNmM0M2Y5ZWQzYThjMGQ3MmE1Nzc4MGFiNDY0YjZiNzdiZDA4YTYwNDNlYWJiNjIxNzg2NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t6vb737JrBDTdFo_DYhng_YB3e-kSfjlkiEHvtbXDx8">

大佬是怎么解决这个问题的啊
