### ISSUE TITLE
Suspected native memory leak in JavaCV when using FFmpegFrameGrabber

### ISSUE THREAD

**Issue by kennovv** [bytedeco/javacv#2371]
Hello,

I have been struggling for several months with a native memory growth issue in production in a Spring Boot Java service that uses JavaCV to process incoming media files.

The service performs only a few operations with `FFmpegFrameGrabber`:
- Retrieves the media file's size and duration
- Generates preview images if the file is a video

However, the native memory usage of the service grows continuously during operation.
To work around this, I am forced to either restart the service periodically or keep increasing its memory limit.

Initially, I reviewed the service's legacy code and corrected several inconsistencies that could contribute to the issue.
I also researched similar reports in the JavaCV and JavaCPP GitHub repositories and applied all recommendations.
Specifically, I now:
- Use try-with-resources wherever possible for all JavaCV and JavaCPP types instances 
- Explicitly call `close()` in `finally` blocks for resources where try-with-resources is not feasible due to code structure 
- Wrap operations in a `PointerScope` (created via try-with-resources) before the `FFmpegFrameGrabber`

Unfortunately, none of these changes resolved the issue.

I also attempted to enforce memory limits by setting the following JavaCPP properties:
- `org.bytedeco.javacpp.maxBytes = 256m` (aligned with the ~250 MB Java heap)
- `org.bytedeco.javacpp.maxPhysicalBytes = 576m` (256 MB native + 256 MB heap + 64 MB extra buffer)

Despite this, after some time of successful operation, the service fails with:

```txt
ERROR com.mycompany.contentmanagementservice.domain.mediafiles.MediaFileService [http-nio-11513-exec-31] Fatal error in JavaCV native call
java.lang.OutOfMemoryError: Cannot allocate new PointerPointer(8): totalBytes = 24, physicalBytes = 716M
        at org.bytedeco.javacpp.PointerPointer.<init>(PointerPointer.java:151)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:934)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:916)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:911)
        at com.mycompany.contentmanagementservice.domain.mediafiles.MediaFileService.processMediaFile(MediaFileService.java:89)
        ...
```

The service processes only a small number of media files (typically 2–3 MB each) over its lifetime. Far too little to justify exceeding specified limits.

To help investigate, I have created a minimal reproduction project on GitHub:
[JavaCVprofiling](https://github.com/KenFromNN/JavaCVprofiling) 

The core logic is in the [`ThumbnailGenerator`](https://github.com/KenFromNN/JavaCVprofiling/blob/main/src/main/java/org/bytedeco/javacv/profiling/ThumbnailGenerator.java) class.
It almost 100% mirrors the production code.

Could you please review it and advise whether I am missing anything critical for proper resource management or native memory control?

Additionally, I profiled this test application using [async-profiler](https://github.com/async-profiler/async-profiler) in `nativemem` mode (as described in its [Native Memory Leaks documentation](https://github.com/async-profiler/async-profiler/blob/master/docs/ProfilingModes.md#native-memory-leaks)).

While I am not an expert in native profiling, it seems that the report shows a large number of native allocations without corresponding `free()` calls, suggesting a possible leak.
I have attached both the async-profiler report and an NMT (Native Memory Tracking) report for your reference:

- [native-leaks.html](https://github.com/user-attachments/files/24236340/native-leaks.html)
- [nmt-final.log](https://github.com/user-attachments/files/24236341/nmt-final.log)

Thank you very much for your time and support, I would greatly appreciate any guidance on how to resolve this problem.

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.12. And if that still doesn't work, please try again with the snapshots:
https://central.sonatype.com/service/rest/repository/browse/maven-snapshots

**Comment by saudet** [comment]
And you're not calling FrameGrabber.close() anywhere. You'll need to call the close() method if you do not want any leaks.

**Comment by kennovv** [comment]
Hello @saudet 

I am already on JavaCV version `1.5.12`.

The `org.bytedeco.javacv.FFmpegFrameGrabber` extends the `org.bytedeco.javacv.FrameGrabber` which implements the `java.io.Closeable` interface.

I am using the `FFmpegFrameGrabber` in try-with-resources statement:

``` java
try (PointerScope scope = new PointerScope();
        FFmpegFrameGrabber grabber =
            FFmpegFrameGrabber.createDefault(fileInfo.getFilePath().toString())) {
   ...
}
```

Therefore when the try block finishes, either normally or due to an exception, the `close()` method of the resource must be automatically called. 

Anyway, I'll try to change my code to call `close()` explicitly and let you know is anything changed.

**Comment by saudet** [comment]
Ah, I'm sorry. I missed that.

It would help to know if the issue is happening in FFmpegFrameGrabber, OpenCVFrameConverter, or Java2DFrameConverter

**Comment by Rivka-Shaked** [comment]
@kennovv 
Has the issue been solved?
I have the same issue. 
https://github.com/bytedeco/javacv/issues/2378

**Comment by saudet** [comment]
No, still waiting to know if this an issue with FFmpegFrameGrabber, OpenCVFrameConverter, or Java2DFrameConverter. Please let me know when you know

**Comment by kennovv** [comment]
> [@kennovv](https://github.com/kennovv) Has the issue been solved? I have the same issue. [#2378](https://github.com/bytedeco/javacv/issues/2378)

No unfortunately :-(

I attempted running my test profiling application multiple times (with and without JIT compiler) and attempted to understand something from the report produced. Unfortunately the report remains complete mystery to me because I have almost none experience in profiling native code for memory leaks.

In my production application I applied workaround and completely replaced JavaCV with direct calls of FFmpeg/FFprobe processes. Had to create my own Docker image with both Java and FFmpeg 8 included for this purpose.
Of course all this for the price of performance because processes execution is much slower than calling JavaCV operations. Luckily my applications workload allows it for now.

For the future if the load will grow I am thinking about trying something else. Probably implement required operations with media files in Rust library and call it via JNI. I wish I could use existing Java solutions of course, but it seems that there are very few "alive" alternatives available and JavaCV looks like the only one more or less actively supported.

**Comment by saudet** [comment]
If you just need the ffmpeg program, no need to use Docker, we can call it from Java just fine:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by Rivka-Shaked** [comment]
I isolated the issue and discovered it related to FFmpegFrameGrabber:
My code contains just initializing of the video:

 `try (FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(videoPath.toFile())) {         
       grabber.stop();
       grabber.release();
       grabber.close();
    }`

And the memory is still not reduced after finishing the process.
Any idea?

We are a big company, and we need a quick solution to this issue.

**Comment by saudet** [comment]
Ok, it's good to know it's an issue with FFmpegFrameGrabber, however I'm unable to reproduce this issue here. It must be related to the codec you are using. Some of them are quite buggy, so try to use another one.

**Comment by Rivka-Shaked** [comment]
I use this artifact:  org.bytedecoorg.bytedeco.javacv - 1.5.12. This is the latest version.
What should I replace?

**Comment by Rivka-Shaked** [comment]
The video files we used now are: video/webm; codecs=vp9,opus or video/webm; codecs=vp8,opus
Do you know an issue with this type?

**Comment by saudet** [comment]
Not that I know of, but please try with more popular codecs like H.264 and AAC, and if those work fine, then we'll know it's a problem with the codecs for VP8, VP9, and Opus.

**Comment by Rivka-Shaked** [comment]
Pay attention that if I run this application locally - in Windows - The issue isn't reproduced. (The memory isn't increased without being reduced.)  Any idea?

**Comment by saudet** [comment]
If this happens only on Linux, you'll need to make sure to call Pointer.trimMemory() in your loops somewhere. Did you make sure to call Pointer.trimMemory() regularly in your application?

**Comment by Rivka-Shaked** [comment]
No. How can I use this method? It is a private method in the Pointer class.

**Comment by saudet** [comment]
Please try again with the snapshots: https://central.sonatype.com/service/rest/repository/browse/maven-snapshots

**Comment by saudet** [comment]
This should be fixed in JavaCV 1.5.13, but please let me know if not. Thanks for reporting and for testing!

**Comment by Rivka-Shaked** [comment]
I didn't try the snapshot because our company has a configured Nexus and was not allowed to download this version.
My issue wasn't fixed.

**Comment by saudet** [comment]
@Rivka-Shaked If you're having problems with FFmpegFrameRecorder, you'll need to try the fix for issue #2356

**Comment by kennovv** [comment]
So, the recommendation is to get JavaCV version 1.5.13 and call static method `Pointer.trimMemory()` at the end of media file processing?
Something like:

```java
  public static void processMediaFile(final FileInfoDomain fileInfo) {
    try (PointerScope scope = new PointerScope();
        FFmpegFrameGrabber grabber =
            FFmpegFrameGrabber.createDefault(fileInfo.getFilePath().toString())) {
      grabber.start();
      // ... do some ops
    } catch (FrameGrabber.Exception exc) {
      throw new IllegalStateException("Error processing media in JavaCV", exc);
    } catch (Error err) {
      // Catching, logging and re-throwing error happened in JavaCV native library call
      System.err.println("\nFatal error in JavaCV native call");
      throw err;
    }
    finally {
      Pointer.trimMemory();
    }
  }
```

**UPD**: oh, I just noticed that you have added `Pointer.trimMemory()` calls into JavaCV code [here](https://github.com/bytedeco/javacv/commit/3c65f93a6de1edf27cc6df6f1314b4a4e4af5fb0). Will try to do some tests with my test app, thank you!

Is it still recommended to have the `PointerScope` in try-with-resource block?

**Comment by saudet** [comment]
I've added calls to Pointer.trimMemory() in commit https://github.com/bytedeco/javacv/commit/3c65f93a6de1edf27cc6df6f1314b4a4e4af5fb0 so you can call it if you want, but it's not necessary as per the sample code you are giving me, no, but I cannot answer any of your questions without giving me some actual sample code to reproduce your issue! It's all guesswork here. If you'd like me to try to debug this you'll need to provide me with actual code that doesn't work like you expect it to work.

If you're using Pointer objects directly, yes please try to use PointerScope: 
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by kennovv** [comment]
I found some time to adapt my test application to collect native memory statistics (not yet committed changes into my GitHub repository though).

I performed two experiments with JavaCV 1.5.12 and 1.5.13 processing 16 MB video file in 20 threads, 10000 invocations total.
Please find memory summary reports below.

**JavaCV 1.5.12:**
```log
=== Memory Profiling Run: javacv_1_5_12 ===
Start time: 2026-03-08T17:07:06.301328799
PID: 828639
OS: Linux


=== FINAL SUMMARY ===
End time: 2026-03-08T17:13:15.847504786
Termination reason: normal completion

=== MEMORY STATISTICS ===
Initial RSS: 47904 KB (46.78 MB)
Final RSS: 2091372 KB (2042.36 MB)
Peak RSS: 11141000 KB (10879.88 MB)
Total memory delta: +50753196 KB (+49563.67 MB)

=== PER-TASK STATISTICS ===
Total tasks: 10000
Average delta per task: +5075.320 KB
TREND: LIKELY LEAK (positive growth per task)
```

**JavaCV 1.5.13:**
```log
=== Memory Profiling Run: javacv_1_5_13 ===
Start time: 2026-03-08T17:18:39.186643594
PID: 919749
OS: Linux


=== FINAL SUMMARY ===
End time: 2026-03-08T17:26:12.271480674
Termination reason: normal completion

=== MEMORY STATISTICS ===
Initial RSS: 48080 KB (46.95 MB)
Final RSS: 567712 KB (554.41 MB)
Peak RSS: 11075692 KB (10816.11 MB)
Total memory delta: +9886976 KB (+9655.25 MB)

=== PER-TASK STATISTICS ===
Total tasks: 10000
Average delta per task: +988.698 KB
TREND: LIKELY LEAK (positive growth per task)
```

It seems that the change applied in release 1.5.13 improved memory utilization indeed.
Yet, it seems that not all leaks are fixed unfortunately.

**Comment by saudet** [comment]
@kennovv Thanks for testing! If you can reproduce this issue with only FFmpegFrameGrabber and using data that isn't private to your organization, please let me know!
