### ISSUE TITLE
Error while trying to build latest source code

### ISSUE THREAD

**Issue by tomerhatav** [bytedeco/javacv#293]
"could not resolve dependencies for project..."

anyone succeded building from the latest source code with ffmpeg 2.8.4??

**Comment by saudet** [comment]
Rebuild JavaCPP and the Presets as well:
https://github.com/bytedeco/javacpp-presets/#build-instructions

**Comment by tomerhatav** [comment]
@saudet I successfully build JavaCPP, but when trying to build the Presets I get this error as I mentioned above.

I did mvn install at the root of javacpp-presets-master folder but I get this error.

**Comment by saudet** [comment]
Try to run the commands inside the `ffmpeg` subdirectory instead.

**Comment by tomerhatav** [comment]
@saudet I tried that too, but know the error is "...Could not parse "libavutil/avutil.h": File does not exist

**Comment by saudet** [comment]
That means you forgot to run the `cppbuild.sh` script. Please try to follow the instructions here:
https://github.com/bytedeco/javacpp-presets/#build-instructions

**Comment by tomerhatav** [comment]
Do I need android NDK to build from source?

**Comment by saudet** [comment]
If you're building for Android, yes:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#android-arm-and-x86

**Comment by tomerhatav-zent** [comment]
Well I did everything the instructions said but now I get this error: "[ERROR] Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.6 @ "

I'm trying to build on mac. I installed NDK,JDK AND MAVEN.

**Comment by tomerhatav** [comment]
Well I did everything the instructions said but now I get this error: "[ERROR] Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.6 @ "

I'm trying to build on mac. I installed NDK,JDK AND MAVEN.

**Comment by saudet** [comment]
It sounds like you're using an old version of Maven. Try to upgrade to the latest version:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#mac-os-x-x86_64
But I don't recommend using Mac OS X to build for Android. Please try on Linux.

**Comment by tomerhatav** [comment]
@saudet after 5 hours straight of failures I give up.
This is my latest error when trying to build FFmpeg from the presets. (After successfully building JavaCPP)
[ERROR] Failed to execute JavaCPP Builder: Cannot run program "toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++": error=2, No such file or directory

Please Help Me... :(
can you build javacv.jar javacpp.jar ffmpeg.jar and ffmpeg-android-arm for me??
If not, All I have to do is to wait for the next release 1.2.

**Comment by saudet** [comment]
Check the comments inside the parent pom.xml file. They will tell you which
properties you need to set to indicate the path to where you extracted the
NDK.

BTW, why do you need 2.8.4? What's missing from 2.8.1?

**Comment by tomerhatav** [comment]
The "java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil in Marshmallow is fixed in this latest commit?
if not, so I don't need to upgrade to 2.8.4

**Comment by saudet** [comment]
I don't think it's fixed, no. It sounds like the FFmpeg team can't do anything about the limitations that Google wants to impose on Android applications.

**Comment by tomerhatav** [comment]
So basically what you saying is that this issue will never be fixed and many production apps that use this amazing library (javacv+ffmpeg) soon will be doomed?

**Comment by saudet** [comment]
No, I'm sure Google is going to do something about this one way or the
other. They have cash to burn and need FFmpeg for their own products. :)
