### ISSUE TITLE
Unsatisfied link error for libjniopencv_core.so on Android.

### ISSUE THREAD

**Issue by nextgensh** [bytedeco/javacv#386]
Hi,

I am using javacv-bin-1.1 in one of my apps. I have included the .jar files into my build as dependencies. 
However when I run my app, it is unable to find libjniopencv_core.so and libgnustl_static.so. I am aware that these files can be found opencv-android-arm.jar.

My exact error message is -

```
04-12 13:56:14.342 10908-10908/com.nextgensh.hawkeye E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.nextgensh.hawkeye, PID: 10908
                                                                       java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.nextgensh.hawkeye-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nextgensh.hawkeye-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjniopencv_core.so"
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                           at java.lang.System.loadLibrary(System.java:989)
                                                                           at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
                                                                           at org.bytedeco.javacpp.Loader.load(Loader.java:438)
                                                                           at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                                           at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.Class.forName(Class.java:308)
                                                                           at org.bytedeco.javacpp.Loader.load(Loader.java:413)
                                                                           at org.bytedeco.javacpp.Loader.load(Loader.java:381)
                                                                           at org.bytedeco.javacpp.opencv_core$Size.<clinit>(opencv_core.java:8927)
                                                                           at com.nextgensh.hawkeye.FaceOperations.<init>(FaceOperations.java:33)
                                                                           at com.nextgensh.hawkeye.MainActivity.testOpenCv(MainActivity.java:59)
                                                                           at com.nextgensh.hawkeye.MainActivity.onCreate(MainActivity.java:52)
                                                                           at android.app.Activity.performCreate(Activity.java:6288)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760)
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5944)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
                                                                        Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.nextgensh.hawkeye-2/base.apk"],nativeLibraryDirectories=[/data/app/com.nextgensh.hawkeye-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgnustl_static.so"
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                           at java.lang.System.loadLibrary(System.java:989)
                                                                           at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:597)
                                                                           at org.bytedeco.javacpp.Loader.load(Loader.java:429)
                                                                           at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
                                                                           at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10) 
                                                                           at java.lang.Class.classForName(Native Method) 
                                                                           at java.lang.Class.forName(Class.java:308) 
                                                                           at org.bytedeco.javacpp.Loader.load(Loader.java:413) 
                                                                           at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
                                                                           at org.bytedeco.javacpp.opencv_core$Size.<clinit>(opencv_core.java:8927) 
                                                                           at com.nextgensh.hawkeye.FaceOperations.<init>(FaceOperations.java:33) 
                                                                           at com.nextgensh.hawkeye.MainActivity.testOpenCv(MainActivity.java:59) 
                                                                           at com.nextgensh.hawkeye.MainActivity.onCreate(MainActivity.java:52) 
                                                                           at android.app.Activity.performCreate(Activity.java:6288) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760) 
                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:145) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5944) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
```

In order to debug I manually extracted the .so files from the .jar and put them in /system/lib/ on a rooted phone as well as /data/app/[app name]/lib/arm/ .

However none of these methods seem to work. 

Am I missing out on something ?

Tools -

Phone - Android 5.0
Android Studio 2.0.0

Thanks!

**Comment by saudet** [comment]
Please try again with the latest SNAPSHOT binaries available here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0-1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.2-SNAPSHOT/

**Comment by saudet** [comment]
Version 1.2 has been released, so you could  try again with that version? Thanks!

**Comment by iamyellow** [comment]
same error here. tried w/ the latest version 1.2.
i've also reported here:
https://github.com/bytedeco/javacpp-presets/issues/178

**Comment by saudet** [comment]
@iamyellow Please make sure your device is installing JNI libraries properly:
The Perils of Loading Native Libraries on Android
https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db

**Comment by iamyellow** [comment]
hey! it worked! :) 

in some user had the same problem, i'm posting the code we used in order to _re-link_ the native libraries. also, it must be executed **before** any call to javacv methods / classes.

```
ReLinker.Logger logger = new ReLinker.Logger() {
    @Override
    public void log(String message) {
        Log.v(TAG, "(relinker) " + message);
    }
};
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_core");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_core");
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_imgcodecs");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_imgcodecs");
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_imgproc");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_imgproc");
```

anyway, I'd like to ask a final question about this. do we need all the libopencv_*.so and  libjniopencv_*.so libraries or just those we're actually using? I mean, in our case we relinked those libraries we're importing statically. So, is it safe remove from libs/[armeabi,x86,etc.] e.g. fetaures2d, calib3d, etc.? I mean, those libraries we're not importing statically. 

thanks a lot for your help and the amazing work you've done!

**Comment by saudet** [comment]
Great! Feel free to create a wiki page to make this more visible and help others.

As for which lib you need or not, just leave them out and if your app still works, you don't need them :)

**Comment by iamyellow** [comment]
sure I will update the wiki. what does it make more sense? javacv or javacpp wiki?

**Comment by saudet** [comment]
I guess the javacpp-presets one:
https://github.com/bytedeco/javacpp-presets/wiki
Create a new page there! Thanks a lot

**Comment by iamyellow** [comment]
done! 
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-(a-real-experience)

ps. i'm not a native English writer/speaker, feel free to correct any typo, expression, freak stuff ;)

**Comment by saudet** [comment]
Awesome!

**Comment by N0un** [comment]
Hi! Sorry but I still have this problem. On some devices (I'm lucky having one!), app failed with this trace:

```
Exception java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_log_format_line" referenced by "libjniavutil.so"...
java.lang.Runtime.loadLibrary (Runtime.java:364)
java.lang.System.loadLibrary (System.java:526)
org.bytedeco.javacpp.Loader.loadLibrary (Loader.java:726)
org.bytedeco.javacpp.Loader.load (Loader.java:501)
org.bytedeco.javacpp.Loader.load (Loader.java:418)
org.bytedeco.javacpp.avutil.<clinit> (avutil.java:10)
...
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1007)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:4394)
android.app.ActivityThread.access$1600 (ActivityThread.java:141)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1273)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5072)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:793)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:609)
dalvik.system.NativeStart.main (NativeStart.java)
arrow_drop_down

Caused by java.lang.UnsatisfiedLinkError: Couldn't load gnustl_static from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.*****.apk"],nativeLibraryDirectories=[/data/app-lib/com.*****, /vendor/lib, /system/lib]]]:
findLibrary returned null
java.lang.Runtime.loadLibrary (Runtime.java:358)
java.lang.System.loadLibrary (System.java:526)
org.bytedeco.javacpp.Loader.loadLibrary (Loader.java:726)
org.bytedeco.javacpp.Loader.load (Loader.java:492)
org.bytedeco.javacpp.Loader.load (Loader.java:418)
org.bytedeco.javacpp.avutil.<clinit> (avutil.java:10)
...
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1007)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:4394)
android.app.ActivityThread.access$1600 (ActivityThread.java:141)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1273)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5072)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:793)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:609)
dalvik.system.NativeStart.main (NativeStart.java)
```
 I'm using FFmpeg preset (3.1.2-1.2) with JavaCPP (1.2.7) on Android. I've got the ffmpeg-android-arm.jar and ffmpeg-android-x86.jar files in my Android Studio "moduleName"/libs. I extract .so and put them to "moduleName"/src/main/jniLibs/{armeabi/x86}. Also, I added this code at the start of the application:

```
		ReLinker.Logger logger = new ReLinker.Logger() {

			@Override
			public void log(String szMessage)
			{
				Logger.debug("[ReLinker] %s", szMessage);
			}
		};

		ReLinker.log(logger).recursively().loadLibrary(this, "jniavcodec");
		ReLinker.log(logger).recursively().loadLibrary(this, "avcodec");
		ReLinker.log(logger).recursively().loadLibrary(this, "jniavdevice");
		ReLinker.log(logger).recursively().loadLibrary(this, "avdevice");
		ReLinker.log(logger).recursively().loadLibrary(this, "jniavfilter");
		ReLinker.log(logger).recursively().loadLibrary(this, "avfilter");
		ReLinker.log(logger).recursively().loadLibrary(this, "jniavformat");
		ReLinker.log(logger).recursively().loadLibrary(this, "avformat");
		ReLinker.log(logger).recursively().loadLibrary(this, "jniavutil");
		ReLinker.log(logger).recursively().loadLibrary(this, "avutil");
		ReLinker.log(logger).recursively().loadLibrary(this, "jnipostproc");
		ReLinker.log(logger).recursively().loadLibrary(this, "postproc");
		ReLinker.log(logger).recursively().loadLibrary(this, "jniswresample");
		ReLinker.log(logger).recursively().loadLibrary(this, "swresample");
		ReLinker.log(logger).recursively().loadLibrary(this, "jniswscale");
		ReLinker.log(logger).recursively().loadLibrary(this, "swscale");
```
And now, this is my trace:

```
12-08 11:02:36.240 25470-25470/com.***** E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        java.lang.UnsatisfiedLinkError: Cannot load library: find_library[1201]:    96 'libswresample.so' failed to load previously
                                                                            at java.lang.Runtime.load(Runtime.java:340)
                                                                            at java.lang.System.load(System.java:521)
                                                                            at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
                                                                            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:198)
                                                                            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                                                                            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
                                                                            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:189)
                                                                            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
                                                                            at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
                                                                            at com..*****.app.CVApplication.onCreate(CVApplication.java:169)
                                                                            at com..*****.ProductCVApplication.onCreate(ProductCVApplication.java:12)
                                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
                                                                            at android.app.ActivityThread.access$1300(ActivityThread.java:130)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                            at android.os.Looper.loop(Looper.java:137)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                            at dalvik.system.NativeStart.main(Native Method)

```

Is there something I forgot?

**Comment by saudet** [comment]
Could you try again with the just released JavaCV 1.3?

**Comment by N0un** [comment]
This is what I did but failed again. But actually I have a good new: NOW IT WORKS!!
The problem was.......... loading libraries **in the right order** !

Order is:

```
ReLinker.log(logger).recursively().loadLibrary(this, "avutil");
ReLinker.log(logger).recursively().loadLibrary(this, "jniavutil");
ReLinker.log(logger).recursively().loadLibrary(this, "swresample");
ReLinker.log(logger).recursively().loadLibrary(this, "jniswresample");
ReLinker.log(logger).recursively().loadLibrary(this, "avcodec");
ReLinker.log(logger).recursively().loadLibrary(this, "jniavcodec");
ReLinker.log(logger).recursively().loadLibrary(this, "swscale");
ReLinker.log(logger).recursively().loadLibrary(this, "jniswscale");
ReLinker.log(logger).recursively().loadLibrary(this, "postproc");
ReLinker.log(logger).recursively().loadLibrary(this, "jnipostproc");
ReLinker.log(logger).recursively().loadLibrary(this, "avformat");
ReLinker.log(logger).recursively().loadLibrary(this, "jniavformat");
ReLinker.log(logger).recursively().loadLibrary(this, "avfilter");
ReLinker.log(logger).recursively().loadLibrary(this, "jniavfilter");
ReLinker.log(logger).recursively().loadLibrary(this, "avdevice");
ReLinker.log(logger).recursively().loadLibrary(this, "jniavdevice");
```

**Comment by saudet** [comment]
Of course, please feel free to add info to the wiki page! Thanks

FYI, we can find the proper order by setting the "org.bytedeco.javacpp.logger.debug" system property to "true" and looking at the result in the log.

**Comment by N0un** [comment]
Thanks for info, I updated the related Wiki page.
