### ISSUE TITLE
Video frames lost at end of Grabbing and Recording session

### ISSUE THREAD

**Issue by techstroke** [bytedeco/javacv#50]
My friend posted this on google code but now I'm posting this here , the problem is that we are trying to apply some opencv effects to a video file and then save results to a new file (mp4 container with x264/AAC) , the output video file is ok and audio is also there , but frames in the last 2-3 seconds of video are gone every time (we tested it with 5 sec/ 12 sec and a 30 sec video to be sure) , we can hear the audio but video just stays there frozen . (problem persist on both Android 4.4.4 & Linx x64 Ubuntu too )

Code fragment - 

```
import static org.bytedeco.javacpp.avcodec.AV_CODEC_ID_AAC;
import static org.bytedeco.javacpp.avcodec.AV_CODEC_ID_H264;
import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;
import static org.bytedeco.javacpp.opencv_highgui.*;

import java.io.File;

import org.bytedeco.javacpp.opencv_core.IplImage;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;

public class Test {
    public static void main(String []args) { 
        File file = new File("/home/vivek/test.mp4");

        // IplImage captured_frame = null;
        //;
        //FFmpegFrameRecorder recorder = null;

        // recorder.setFrameRate(25);
        // recorder.setVideoBitrate(700000);

        try {
            FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(file.getAbsolutePath());
            frameGrabber.start();
            //Log.d("bharat:", "frame count " + frameGrabber.getLengthInFrames() + "");
            FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("/home/vivek/out.mp4", frameGrabber.getImageWidth(), frameGrabber.getImageHeight(), 2);
            recorder.setVideoCodec(AV_CODEC_ID_H264);
            recorder.setFormat("mp4");
            // necessory becoz of audio..
            System.out.println(" frame rate" + frameGrabber.getFrameRate());
            System.out.println(" Sample Rate"+frameGrabber.getSampleRate() );
            System.out.println(" Sample Format"+ frameGrabber.getSampleFormat() );
            //System.out.println(" Sample Rate"+ );

            recorder.setFrameRate(frameGrabber.getFrameRate());
            recorder.setSampleFormat(frameGrabber.getSampleFormat());
            recorder.setSampleRate(frameGrabber.getSampleRate());

            recorder.setAudioCodec(AV_CODEC_ID_AAC);
            recorder.start();



            long currentTimeMillis = System.currentTimeMillis();

            int count = 0;
            int totalcount = 0;
            int soundCount = 0;
            while (true) {
                try {
                    totalcount++;
                    Frame grabFrame = frameGrabber.grabFrame();

                    if (grabFrame == null) {
                        System.out.println("!!! Failed cvQueryFrame");
                        break;
                        }
                    if (grabFrame.image != null) {
                        if (count > 390) {
//                          ByteBuffer asBuffer = grabFrame.image.arraySize();
//                          byte[] array = asBuffer.array();
//                          String d = "";
//                          for (int i = 0; i < array.length; i++) {
//                              d += " " + array[i];
//                          }
                            //Log.d("bharat", "frame:" + count + " data:" +  grabFrame.image.arraySize());
                        }
                        count++;
                         IplImage frame_copy = cvCreateImage(cvSize(grabFrame.image.width(),
                         grabFrame.image.height()), IPL_DEPTH_8U, 1);
                         cvCvtColor(grabFrame.image, frame_copy, CV_RGB2GRAY);
                         grabFrame.image = frame_copy;
                         //cvSaveImage(filePath + File.separator + "image" +
                         //count++ + ".jpg", grabFrame.image);
                    } else {
                        if (grabFrame.samples == null) {
                            System.out.println("anonymous data :");
                        }
                        // Log.d("bharat:", "sound data :" + sound);
                    }
                    recorder.setTimestamp(frameGrabber.getTimestamp());
                    recorder.record(grabFrame);

                } catch (Exception e) {
                    System.out.println("exception " + e);
                    e.printStackTrace();
                }

            }
            System.out.println("frame done, "+soundCount + " " + count + " " + totalcount);
            recorder.stop();
            recorder.release();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

I also tried above code  with alterations on my ubuntu x64 and I got the output file but the problem still persisted . When i tried *\* ffplay -loglevel debug out.mp4 *\* I got the following  error lines 

[mp4 @ 0x7f6be4613e00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 30720 >= 30720
[libx264 @ 0x7f6be460a080] non-strictly-monotonic PTS
also a  _Frame num gap 1 5_ line was in debug log along with above

While in my eclipse console i got something like this ,

`exception org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video frame.
org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video frame.
    at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:725)
    at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:629)
    at org.bytedeco.javacv.FrameRecorder.record(FrameRecorder.java:290)
    at Test.main(Test.java:85)`

little bit of googling hinted that this issue is related to pts calculation if that helps !

**Comment by saudet** [comment]
Does this still happen with the latest version of JavaCV? If so, let's reopen this as a bug. Thanks!

**Comment by saudet** [comment]
I think this commit should fix this: https://github.com/bytedeco/javacv/commit/fb2206de652e2777b3e0c6621dc3c7d47fc16bdf
Let me know! Thanks

**Comment by liangkuai** [comment]
Hi, guys
When I upload file to RTMP server, I get a fault all the time.
```
[libx264 @ 00000000266ccc00] non-strictly-monotonic PTS
```
And when I open rtmp stream in VLC, the video play fast abnormally.
I need some help...

**Comment by kmandayam** [comment]
Can anyone confirm if this if this works? I am using 1.3.1 and I am still facing this issue

**Comment by saudet** [comment]
@kmandayam Please provide a code snippet to reproduce this issue, thank you!

**Comment by kmandayam** [comment]
I'm trying to merge audio while video recording. I'm doing it onPreviewFrame: 

@Override
        public void onPreviewFrame(byte[] data, Camera camera)
        {
            try
            {
                if (songPath != null)
                {
                    audioFrame = audioGrabber.grabFrame(true, false, false, false);
                }
            }
            catch (FrameGrabber.Exception e)
            {
                e.printStackTrace();
            }
            /* get video data */
            if (yuvIplImage != null && isRecording)
            {
                try
                {
                    ((ByteBuffer) yuvIplImage.image[0].position(0)).put(data);
                    timestamp = 1000 * (System.currentTimeMillis() - startTime);
                    if (songPath == null)
                    {
                        if (timestamp > recorder.getTimestamp())
                        {
                            recorder.setTimestamp(timestamp);
                        }
                    }
                    else
                    {
                        // Updating timestamp if audio is chosen from the library
                        if (recorder.getTimestamp() <= audioGrabber.getTimestamp() )
                        {
                            recorder.setTimestamp(audioGrabber.getTimestamp());
                        }
                    }

                    if (useFilter)
                    {
                        Frame frame2;
                        if (useNexusFilter())
                        {
                            nexusFilter.push(yuvIplImage);
                            while ((frame2 = nexusFilter.pull()) != null)
                            {

                                if (audioFrame != null)
                                {
                                    recorder.record(audioFrame);
                                }
                                recorder.record(frame2);
                            }
                        }
                        else
                        {
                            filter.push(yuvIplImage);
                            while ((frame2 = filter.pull()) != null)
                            {

                                if (audioFrame != null)
                                {
                                    recorder.record(audioFrame);
                                }
                                recorder.record(frame2);
                            }
                        }
                    }
                    else
                    {
                        if (audioFrame != null)
                        {
                            recorder.record(audioFrame);
                        }
                        recorder.record(yuvIplImage);
                    }
                }
              
                catch (FFmpegFrameRecorder.Exception | FrameFilter.Exception)
                {
                    e.printStackTrace();
                }
            }
        }

I'm initializing and updating the FrameGrabber and recorder in surfaceCreated:

 @Override
        public void surfaceCreated(SurfaceHolder holder)
        {
            try
            {
                stopPreview();
                camera.setPreviewDisplay(holder);
                this.camera.setPreviewCallback(CameraView.this);
                if (songPath != null)
                {
                    // Initialize audioGrabber
                    audioGrabber = new FFmpegFrameGrabber(songPath);
                    audioGrabber.start();
                    audioGrabber.setFormat("mp3");
                    audioGrabber.setFrameRate(FRAME_RATE);
                    audioGrabber.setSampleRate(AUDIO_RATE);

                    // Update recorder settings
                    recorder.setSampleRate(audioGrabber.getSampleRate());
                    recorder.setFrameRate(FRAME_RATE);
                    recorder.setAudioChannels(audioGrabber.getAudioChannels());
                    recorder.setSampleRate(AUDIO_RATE);
                }
            }
            catch (FrameGrabber.Exception e)
            {
                e.printStackTrace();
            }
            catch (IOException exception)
            {
                camera.release();
                camera = null;
            }
        }


I'm also losing few seconds of audio before the video ends. Please take a look and let me know if I am going wrong somewhere

**Comment by kmandayam** [comment]
I'm trying to merge audio while video recording. I'm doing it onPreviewFrame:

        @Override
        public void onPreviewFrame(byte[] data, Camera camera)
        {
            try
            {
                if (songPath != null)
                {
                    audioFrame = audioGrabber.grabFrame(true, false, false, false);
                }

            }
            catch (FrameGrabber.Exception e)
            {
                e.printStackTrace();
            }
            /* get video data */
            if (yuvIplImage != null && isRecording)
            {
                try
                {
                    ((ByteBuffer) yuvIplImage.image[0].position(0)).put(data);
                    timestamp = 1000 * (System.currentTimeMillis() - startTime);
                    if (songPath == null)
                    {
                        if (timestamp > recorder.getTimestamp())
                        {
                            recorder.setTimestamp(timestamp);
                        }
                    }
                    else
                    {
                        // Updating timestamp if audio is chosen from the library
                        if (recorder.getTimestamp() <= audioGrabber.getTimestamp() )
                        {
                            recorder.setTimestamp(audioGrabber.getTimestamp());
                        }
                    }

                    if (useFilter)
                    {
                        Frame frame2;
                        if (useNexusFilter())
                        {
                            nexusFilter.push(yuvIplImage);
                            while ((frame2 = nexusFilter.pull()) != null)
                            {

                                if (audioFrame != null)
                                {
                                    recorder.record(audioFrame);
                                }
                                recorder.record(frame2);
                            }
                        }
                        else
                        {
                            filter.push(yuvIplImage);
                            while ((frame2 = filter.pull()) != null)
                            {

                                if (audioFrame != null)
                                {
                                    recorder.record(audioFrame);
                                }
                                recorder.record(frame2);
                            }
                        }
                    }
                    else
                    {
                        if (audioFrame != null)
                        {
                            recorder.record(audioFrame);
                        }
                        recorder.record(yuvIplImage);
                    }
                }
                catch (NullPointerException e)
                {
                    e.printStackTrace();
                }
                catch (FFmpegFrameRecorder.Exception | FrameFilter.Exception | BufferOverflowException e)
                {
                    e.printStackTrace();
                }
            }
        }



I'm initializing and updating the FrameGrabber and recorder in surfaceCreated:

 @Override
        public void surfaceCreated(SurfaceHolder holder)
        {
            try
            {
                stopPreview();
                camera.setPreviewDisplay(holder);
                this.camera.setPreviewCallback(CameraView.this);
                if (songPath != null)
                {
                    // Initialize audioGrabber
                    audioGrabber = new FFmpegFrameGrabber(songPath);
                    audioGrabber.start();
                    audioGrabber.setFormat("mp3");
                    audioGrabber.setFrameRate(FRAME_RATE);
                    audioGrabber.setSampleRate(AUDIO_RATE);

                    // Update recorder settings
                    recorder.setSampleRate(audioGrabber.getSampleRate());
                    recorder.setFrameRate(FRAME_RATE);
                    recorder.setAudioChannels(audioGrabber.getAudioChannels());
                    recorder.setSampleRate(AUDIO_RATE);
                }
            }
            catch (FrameGrabber.Exception e)
            {
                e.printStackTrace();
            }
            catch (IOException exception)
            {
                camera.release();
                camera = null;
            }
        }

I'm also losing few seconds of audio before the video ends. Please take a look and let me know if I am going wrong somewhere

**Comment by saudet** [comment]
Does this happen only on Android or can you reproduce that with Java SE as
well?

**Comment by kmandayam** [comment]
@saudet I've only tried it on android. Not sure how to reproduce it with Java SE

**Comment by saudet** [comment]
@kmandayam Could you elaborate on why you're not sure how to reproduce this issue with Java SE?

**Comment by kmandayam** [comment]
@saudet Sorry for the late reply. I don't have a lot of experience working with javacv, so I don't know how to replicate this problem.

**Comment by kmandayam** [comment]
It works fine when I don't try to merge a separate audio file with the video (ie using the mic). All the frames are retained.

**Comment by saudet** [comment]
I see, audio and video need to have the same length, or the shortest might
get cut, yes.

**Comment by kmandayam** [comment]
Well, since I am trying to merge audio while I record video, even if I stop recording mid way through the audio file, it still gets cropped. Could it have to do anything with the sample rate or frame rate?

**Comment by saudet** [comment]
It's possible that more frames would be needed because of incorrect rates,
yes.
