### ISSUE TITLE
unable to load this jars?

### ISSUE THREAD

**Issue by srajesh529** [bytedeco/javacv#85]
Hi i am unable to load this jars in my android app,i run my app it shoes the runtime errors and shutdown my app? error is no jni on load found....below is my stack trace.please help how to load jars?Thanks in Advance

01-28 13:26:56.185  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /system/lib/libc.so 0x41e201e0, skipping init
01-28 13:26:56.195  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /system/lib/libm.so 0x41e201e0, skipping init
01-28 13:26:56.195  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /system/lib/libz.so 0x41e201e0, skipping init
01-28 13:26:56.195  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /system/lib/libdl.so 0x41e201e0, skipping init
01-28 13:26:56.205  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /system/lib/liblog.so 0x41e201e0, skipping init
01-28 13:26:56.205  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libavutil.so 0x41e201e0
01-28 13:26:56.205  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libavutil.so 0x41e201e0
01-28 13:26:56.205  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-2/libavutil.so 0x41e201e0, skipping init
01-28 13:26:56.205  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavutil.so 0x41e201e0
01-28 13:26:56.205  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavutil.so 0x41e201e0
01-28 13:26:56.225  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ GC_FOR_ALLOC freed 405K, 5% free 9667K/10104K, paused 12ms, total 12ms
01-28 13:26:56.245  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libswresample.so 0x41e201e0
01-28 13:26:56.245  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libswresample.so 0x41e201e0
01-28 13:26:56.245  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-2/libswresample.so 0x41e201e0, skipping init
01-28 13:26:56.245  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniswresample.so 0x41e201e0
01-28 13:26:56.245  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniswresample.so 0x41e201e0
01-28 13:26:56.255  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libavcodec.so 0x41e201e0
01-28 13:26:56.255  18463-18487/com.tutk.sample.AVAPI W/linker﹕ libavcodec.so has text relocations. This is wasting memory and is a security risk. Please fix.
01-28 13:26:56.255  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libavcodec.so 0x41e201e0
01-28 13:26:56.255  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-2/libavcodec.so 0x41e201e0, skipping init
01-28 13:26:56.255  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavcodec.so 0x41e201e0
01-28 13:26:56.255  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavcodec.so 0x41e201e0
01-28 13:26:56.265  18463-18488/com.tutk.sample.AVAPI E/ret value for audio is﹕ <><>0
01-28 13:26:56.315  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ GC_FOR_ALLOC freed 428K, 5% free 9750K/10212K, paused 12ms, total 12ms
01-28 13:26:56.335  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libavformat.so 0x41e201e0
01-28 13:26:56.335  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libavformat.so 0x41e201e0
01-28 13:26:56.335  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-2/libavformat.so 0x41e201e0, skipping init
01-28 13:26:56.335  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavformat.so 0x41e201e0
01-28 13:26:56.335  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavformat.so 0x41e201e0
01-28 13:26:56.365  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libpostproc.so 0x41e201e0
01-28 13:26:56.365  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libpostproc.so 0x41e201e0
01-28 13:26:56.365  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-2/libpostproc.so 0x41e201e0, skipping init
01-28 13:26:56.365  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libjnipostproc.so 0x41e201e0
01-28 13:26:56.365  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libjnipostproc.so 0x41e201e0
01-28 13:26:56.385  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libswscale.so 0x41e201e0
01-28 13:26:56.385  18463-18488/com.tutk.sample.AVAPI E/ret value for audio is﹕ <><>0
01-28 13:26:56.385  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libswscale.so 0x41e201e0
01-28 13:26:56.385  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-2/libswscale.so 0x41e201e0, skipping init
01-28 13:26:56.385  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniswscale.so 0x41e201e0
01-28 13:26:56.385  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniswscale.so 0x41e201e0
01-28 13:26:56.395  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ GC_FOR_ALLOC freed 459K, 5% free 9799K/10296K, paused 13ms, total 13ms
01-28 13:26:56.415  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libavfilter.so 0x41e201e0
01-28 13:26:56.425  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libavfilter.so 0x41e201e0
01-28 13:26:56.425  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-2/libavfilter.so 0x41e201e0, skipping init
01-28 13:26:56.425  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavfilter.so 0x41e201e0
01-28 13:26:56.425  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavfilter.so 0x41e201e0
01-28 13:26:56.435  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libavdevice.so 0x41e201e0
01-28 13:26:56.435  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libavdevice.so 0x41e201e0
01-28 13:26:56.435  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-2/libavdevice.so 0x41e201e0, skipping init
01-28 13:26:56.435  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavdevice.so 0x41e201e0
01-28 13:26:56.435  18463-18487/com.tutk.sample.AVAPI D/dalvikvm﹕ Added shared lib /data/app-lib/com.tutk.sample.AVAPI-2/libjniavdevice.so 0x41e201e0
01-28 13:26:56.445  18463-18487/com.tutk.sample.AVAPI A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000030 (code=1), thread 18487 (Video Thread)

**Comment by saudet** [comment]
Which device is that?

**Comment by srajesh529** [comment]
i am tested samsung s4,galaxy nexus. i put this jars in libs folder javacpp-0.10.jar,javacv-0.10.jar,ffmpeg-2.5.1-0.10.jar,opencv-2.4.10-0.10.jar and opevcv-android-arm.jar,ffmpeg-android-arm.jar extract this jars and put .so files into armeabi folder

**Comment by srajesh529** [comment]
is any other files are required to add?

**Comment by saudet** [comment]
No... Are you sure there isn't more information in the log? It looks like it's filtering out data about the crash.

**Comment by srajesh529** [comment]
thanks for reply,no i am getting error as Error loading class com/googlecode/javacpp/Pointer.?

**Comment by saudet** [comment]
So, using JavaCV 0.10 should fix this then.

**Comment by srajesh529** [comment]
hi issue is not fixed,now i am using JavaCV 0.10,it is shows the errors in runtime and shutdown my app.below is my log. 

01-30 09:59:56.730: I/System.out(21388): Step 2: call IOTC_Connect_ByUID(W6G9ST1FDWYH31CWUMZJ).......
01-30 09:59:57.000: I/System.out(21388): Step 2: call avClientStart(0).......
01-30 09:59:58.131: I/System.out(21388): [Video Thread] Start
01-30 09:59:58.131: E/ret value for video is(21388): <><>2607<><>0
01-30 09:59:58.131: E/videobuffer size ois(21388): <><>>2607
01-30 09:59:58.241: D/dalvikvm(21388): GC_FOR_ALLOC freed 218K, 3% free 9274K/9524K, paused 12ms, total 12ms
01-30 09:59:58.371: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/libc.so 0x41e23f88, skipping init
01-30 09:59:58.371: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/libm.so 0x41e23f88, skipping init
01-30 09:59:58.371: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/libz.so 0x41e23f88, skipping init
01-30 09:59:58.371: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/libdl.so 0x41e23f88, skipping init
01-30 09:59:58.381: D/dalvikvm(21388): GC_FOR_ALLOC freed 348K, 4% free 9441K/9820K, paused 11ms, total 11ms
01-30 09:59:58.391: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/liblog.so 0x41e23f88, skipping init
01-30 09:59:58.391: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavutil.so 0x41e23f88
01-30 09:59:58.391: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavutil.so 0x41e23f88
01-30 09:59:58.391: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavutil.so 0x41e23f88, skipping init
01-30 09:59:58.391: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavutil.so 0x41e23f88
01-30 09:59:58.391: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavutil.so 0x41e23f88
01-30 09:59:58.411: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libswresample.so 0x41e23f88
01-30 09:59:58.411: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libswresample.so 0x41e23f88
01-30 09:59:58.411: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libswresample.so 0x41e23f88, skipping init
01-30 09:59:58.421: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniswresample.so 0x41e23f88
01-30 09:59:58.421: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniswresample.so 0x41e23f88
01-30 09:59:58.421: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavcodec.so 0x41e23f88
01-30 09:59:58.421: W/linker(21388): libavcodec.so has text relocations. This is wasting memory and is a security risk. Please fix.
01-30 09:59:58.421: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavcodec.so 0x41e23f88
01-30 09:59:58.421: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavcodec.so 0x41e23f88, skipping init
01-30 09:59:58.421: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavcodec.so 0x41e23f88
01-30 09:59:58.421: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavcodec.so 0x41e23f88
01-30 09:59:58.481: D/dalvikvm(21388): GC_FOR_ALLOC freed 426K, 5% free 9526K/9984K, paused 11ms, total 11ms
01-30 09:59:58.511: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavformat.so 0x41e23f88
01-30 09:59:58.511: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavformat.so 0x41e23f88
01-30 09:59:58.511: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavformat.so 0x41e23f88, skipping init
01-30 09:59:58.511: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavformat.so 0x41e23f88
01-30 09:59:58.511: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavformat.so 0x41e23f88
01-30 09:59:58.541: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libpostproc.so 0x41e23f88
01-30 09:59:58.541: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libpostproc.so 0x41e23f88
01-30 09:59:58.541: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libpostproc.so 0x41e23f88, skipping init
01-30 09:59:58.541: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjnipostproc.so 0x41e23f88
01-30 09:59:58.541: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjnipostproc.so 0x41e23f88
01-30 09:59:58.561: D/dalvikvm(21388): GC_FOR_ALLOC freed 457K, 5% free 9579K/10072K, paused 12ms, total 12ms
01-30 09:59:58.571: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libswscale.so 0x41e23f88
01-30 09:59:58.571: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libswscale.so 0x41e23f88
01-30 09:59:58.571: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libswscale.so 0x41e23f88, skipping init
01-30 09:59:58.571: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniswscale.so 0x41e23f88
01-30 09:59:58.571: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniswscale.so 0x41e23f88
01-30 09:59:58.591: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavfilter.so 0x41e23f88
01-30 09:59:58.591: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavfilter.so 0x41e23f88
01-30 09:59:58.591: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavfilter.so 0x41e23f88, skipping init
01-30 09:59:58.591: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavfilter.so 0x41e23f88
01-30 09:59:58.591: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavfilter.so 0x41e23f88
01-30 09:59:58.611: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavdevice.so 0x41e23f88
01-30 09:59:58.611: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavdevice.so 0x41e23f88
01-30 09:59:58.611: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavdevice.so 0x41e23f88, skipping init
01-30 09:59:58.611: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavdevice.so 0x41e23f88
01-30 09:59:58.611: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavdevice.so 0x41e23f88
01-30 09:59:58.621: A/libc(21388): Fatal signal 11 (SIGSEGV) at 0x00000030 (code=1), thread 21511 (Video Thread)

**Comment by saudet** [comment]
Ok, so, like I said already, are you sure there isn't more information in the log? It looks like it's filtering out data about the crash.

**Comment by VincentVivian** [comment]
same issue when use javacv 1.1

**Comment by VincentVivian** [comment]
No JNI_OnLoad found in /system/lib/libc.so 0x4136cf68, skipping init
11-18 10:26:23.780 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/libm.so 0x4136cf68, skipping init
11-18 10:26:23.790 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/libz.so 0x4136cf68, skipping init
11-18 10:26:23.790 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/libdl.so 0x4136cf68, skipping init
11-18 10:26:23.790 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /system/lib/liblog.so 0x4136cf68, skipping init
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: Trying to load lib /data/data/org.bytedeco.javacv_android_example/lib/libavutil.so 0x4136cf68
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: Added shared lib /data/data/org.bytedeco.javacv_android_example/lib/libavutil.so 0x4136cf68
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: No JNI_OnLoad found in /data/data/org.bytedeco.javacv_android_example/lib/libavutil.so 0x4136cf68, skipping init
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example D/dalvikvm: Trying to load lib /data/data/org.bytedeco.javacv_android_example/lib/libjniavutil.so 0x4136cf68
11-18 10:26:23.800 14422-14422/org.bytedeco.javacv_android_example W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/bytedeco/javacpp/avutil;
11-18 10:26:23.820 14422-14422/org.bytedeco.javacv_android_example I/dalvikvm: Rejecting re-init on previously-failed class Lorg/bytedeco/javacpp/avutil; v=0x0
11-18 10:26:23.820 14422-14422/org.bytedeco.javacv_android_example W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lorg/bytedeco/javacpp/avcodec$AVPacket;
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example D/AndroidRuntime: Shutting down VM
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40a5e1f8)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime: FATAL EXCEPTION: main
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime: java.lang.ExceptionInInitializerError
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:415)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:381)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.forName(Class.java:217)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:413)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.classForName(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.forName(Class.java:217) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:413) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.classForName(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.Class.forName(Class.java:217) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:413) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.Loader.load(Loader.java:381) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:162) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:176) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:224) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View.performClick(View.java:3511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:14110) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:605) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4426) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
11-18 10:26:23.830 14422-14422/org.bytedeco.javacv_android_example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by VincentVivian** [comment]
android system 4.0.3 show the error ， 5.0 not
